# vim: set noexpandtab: -*- indent-tabs-mode: t -*-
"""
Staged trust store overlay for smoke validation.

During smoke, the just-built package is not yet published and may not
be trusted by the baseline trust store.  The staged trust overlay adds
the build-time signer as a trusted key for the artifact's namespace
(and for any co-deployed sibling artifacts signed by the same kid in
this session), enabling smoke consumers to verify the staged packages.

Composition: staged_trust = baseline_trust ∪ staged_signer

**Two dep classes, two policies (2026-05-18 redesign):**

The caller distinguishes deps by source.  Co-deployed deps are sibling
artifacts being signed by `signer_pubkey_raw` in this same deploy
session -- their `.sig` was generated by us, so smoke must trust our
kid for their namespace.  External dependencies are already-published
packages in the staged package-root, signed by their original
publisher (e.g. a Foundation-signed `mariadb-rpc` consumed by
PushCoin's `singular`).  The deploy signer is NOT authorized to sign
those; the baseline trust store must already cover them.

Policies:

  artifact_namespace + co_deployed_namespaces:
      Add staged signer to namespace.  Inherit any kids the baseline's
      broader pattern already granted (so we don't shadow them).

  external_dependency_namespaces:
      Do NOT add staged signer.  Do NOT write any overlay entry.
      Baseline trust is authoritative; the verifier's longest-prefix-
      wins matcher naturally picks up the baseline grant.  If the
      baseline has no coverage for an external dep, raise loudly --
      that's a pre-existing baseline misconfiguration that would have
      surfaced as an opaque "package signatures not trusted" later.

**Why the split matters.**  Pre-2026-05-18 the API took a single
`dep_namespaces` list and stamped the staged signer on every entry.
Two failure modes resulted:

1.  *Shadowing.*  A more-specific overlay entry with only the new
    signer would beat the broader baseline grant under longest-prefix-
    wins.  E.g. baseline `mariadb.rpc.*` -> [foundation_kid] would be
    shadowed by overlay `mariadb.rpc.managed.*` -> [pushcoin_kid],
    and the Foundation-signed dep would fail trust verification.

2.  *Over-authorization.*  Even with shadowing fixed (inherit baseline
    kids in the overlay entry), the deploy signer would STILL be
    listed as an authorized signer for external dep namespaces it
    has no business signing.  The staged trust is temporary, but
    over-authorizing the app signer for Foundation-owned deps is not
    a clean policy.

The redesigned API closes both holes structurally: the deploy signer
can ONLY land on the artifact's own namespace or on co-deployed
siblings.  External deps are inherit-only.  Reported in
work/drift-deploy-trust-overlay-bug.
"""

from __future__ import annotations

import base64
import hashlib
import json
from pathlib import Path
from typing import Any


def _effective_baseline_kids_for_module(
	namespaces: dict[str, list[str]],
	module_id: str,
) -> set[str]:
	"""Return the kids that an existing namespace map authorizes for
	`module_id` under longest-prefix-wins semantics.

	Mirrors `lang/driftc/packages/trust_v0.py::TrustStore.allowed_kids_for_module`
	(MVP namespace rules: exact match, `<ns>.*` prefix match, longest
	wins, ties union).  Kept as a separate (small) function here so
	the deploy tool doesn't depend on the compiler's TrustStore loader
	for this single query during overlay generation.

	Treats the `namespaces` map as the source of truth -- the caller
	(`build_staged_trust`) is responsible for passing the BASELINE
	state before any new entries are added.
	"""
	best_len = -1
	out: set[str] = set()
	for ns, kids in namespaces.items():
		if ns.endswith(".*"):
			pfx = ns[:-2]
			if module_id == pfx or module_id.startswith(pfx + "."):
				match_len = len(pfx)
			else:
				continue
		else:
			if module_id != ns:
				continue
			match_len = len(ns)
		if match_len > best_len:
			best_len = match_len
			out = set(kids)
		elif match_len == best_len:
			out |= set(kids)
	return out


def build_staged_trust(
	*,
	baseline_trust_path: Path | None,
	signer_pubkey_raw: bytes,
	artifact_namespace: str,
	out_path: Path,
	co_deployed_namespaces: list[str] | None = None,
	external_dependency_namespaces: list[str] | None = None,
) -> None:
	"""
	Build a staged trust store for smoke validation.

	Merges the baseline trust store (if any) with the staged signer's
	public key, authorized for `artifact_namespace.*` and for any
	co-deployed sibling artifacts.  External dependencies are NOT
	authorized for the staged signer -- their baseline trust grant is
	authoritative.

	Args:
		baseline_trust_path: Path to existing trust.json (or None).
		signer_pubkey_raw: 32-byte Ed25519 public key of the signer.
		artifact_namespace: Package namespace to authorize for the
			staged signer (e.g., "net.tls").  The artifact being built
			in this deploy session.
		out_path: Where to write the staged trust.json.
		co_deployed_namespaces: Namespaces of sibling artifacts being
			signed by the SAME staged signer in this deploy session.
			Each gets the staged signer added on top of any baseline
			inheritance.  Pass `None` or `[]` if no sibling artifacts.
		external_dependency_namespaces: Namespaces of already-published
			deps consumed from the staged package-root, signed by their
			original (different) publisher.  Baseline trust is
			authoritative; this list is used ONLY to verify baseline
			coverage exists and to surface misconfigurations early.
			NO overlay entries are written -- the staged signer is
			never authorized for these namespaces.

	Raises:
		ValueError: if any namespace in
			`external_dependency_namespaces` has no baseline trust
			coverage (no exact-match or `*`-pattern that resolves to
			at least one kid).  This catches missing baseline grants
			before they surface as opaque "package signatures not
			trusted" during smoke.
	"""
	# Load baseline or start empty.
	if baseline_trust_path and baseline_trust_path.exists():
		data = json.loads(baseline_trust_path.read_text(encoding="utf-8"))
	else:
		data = {
			"format": "drift-trust",
			"version": 0,
			"keys": {},
			"namespaces": {},
			"revoked": {},
		}

	# Snapshot the baseline namespaces map BEFORE we modify it.  The
	# external-dep coverage check below queries this snapshot so
	# overlay entries written for the artifact / co-deployed siblings
	# don't accidentally satisfy "external dep has baseline coverage".
	baseline_namespaces_snapshot: dict[str, list[str]] = {
		ns: list(kids) for ns, kids in (data.get("namespaces") or {}).items()
	}

	# Compute kid for the signer.
	kid = "ed25519:" + base64.b64encode(
		hashlib.sha256(signer_pubkey_raw).digest()
	).decode("ascii")

	pubkey_b64 = base64.b64encode(signer_pubkey_raw).decode("ascii")

	# Add the signer key if not already present.
	keys = data.setdefault("keys", {})
	if kid not in keys:
		keys[kid] = {
			"algo": "ed25519",
			"pubkey": pubkey_b64,
		}

	namespaces = data.setdefault("namespaces", {})

	def _authorize_namespace_for_staged_signer(ns: str) -> None:
		"""Write (or extend) the `ns` and `ns.*` entries to include the
		staged signer kid, inheriting any kids the baseline's broader
		pattern already granted for that module-id.  Inheritance
		preserves grants like baseline `mariadb.rpc.*` -> [foundation_kid]
		when the artifact's own namespace happens to live under
		`mariadb.rpc.*` (rare for the artifact itself, common for
		co-deployed siblings of an internal-rooted deploy).
		"""
		# Pattern entry: probe with a leaf strictly under `ns` so the
		# longest-match query falls back to the baseline's broader
		# pattern rather than to the about-to-be-written `ns.*`.  The
		# synthetic suffix is reserved (leading underscores aren't
		# valid in user-visible module identifiers).
		pattern = f"{ns}.*"
		pattern_probe = f"{ns}.__staged_overlay_inherit_probe__"
		inherited_pattern = _effective_baseline_kids_for_module(
			baseline_namespaces_snapshot, pattern_probe,
		)
		pattern_kids = list(namespaces.get(pattern, []))
		for inh in sorted(inherited_pattern):
			if inh not in pattern_kids:
				pattern_kids.append(inh)
		if kid not in pattern_kids:
			pattern_kids.append(kid)
		namespaces[pattern] = pattern_kids

		inherited_exact = _effective_baseline_kids_for_module(
			baseline_namespaces_snapshot, ns,
		)
		exact_kids = list(namespaces.get(ns, []))
		for inh in sorted(inherited_exact):
			if inh not in exact_kids:
				exact_kids.append(inh)
		if kid not in exact_kids:
			exact_kids.append(kid)
		namespaces[ns] = exact_kids

	# Authorize the artifact's own namespace (always).
	_authorize_namespace_for_staged_signer(artifact_namespace)

	# Authorize co-deployed sibling namespaces.
	for sibling_ns in (co_deployed_namespaces or []):
		_authorize_namespace_for_staged_signer(sibling_ns)

	# External dependencies: verify baseline coverage exists, write
	# NOTHING.  The staged signer must not be authorized for these
	# namespaces; the baseline's grant for the dep's original
	# publisher is the only authority that should validate the dep's
	# `.sig` during smoke.  Querying the baseline snapshot (not the
	# in-progress `namespaces` map) is important: an artifact /
	# co-deployed entry we just wrote could spuriously appear to
	# "cover" the external dep otherwise.
	missing_coverage: list[str] = []
	for ext_ns in (external_dependency_namespaces or []):
		ext_kids = _effective_baseline_kids_for_module(baseline_namespaces_snapshot, ext_ns)
		# Probe a leaf under the namespace too, since deps may register
		# both exact module-ids and deeper sub-modules.  Either form of
		# baseline coverage is acceptable; only a complete miss is an
		# error.
		if not ext_kids:
			ext_kids_leaf = _effective_baseline_kids_for_module(
				baseline_namespaces_snapshot,
				f"{ext_ns}.__staged_overlay_inherit_probe__",
			)
			if not ext_kids_leaf:
				missing_coverage.append(ext_ns)

	if missing_coverage:
		raise ValueError(
			"external dependency namespaces have no baseline trust "
			"coverage; add a trust grant for the dep's publisher in "
			"the baseline trust store before deploying: "
			f"{sorted(missing_coverage)!r}"
		)

	out_path.parent.mkdir(parents=True, exist_ok=True)
	out_path.write_text(
		json.dumps(data, indent=2, ensure_ascii=False) + "\n",
		encoding="utf-8",
	)


def load_signing_key_seed(key_seed_path: Path) -> bytes:
	"""Load a 32-byte Ed25519 private seed from the canonical Drift
	key-file format (base64 text, possibly trailing newline).

	Decode goes through `lang.drift.crypto.b64_decode` so the strict
	`validate=True` semantics are shared with every other signing
	surface (artifact `.sig`, `.source-attestation`, smoke trust
	extraction).  Without `validate=True`, Python's base64 decoder
	silently ignores non-base64 characters — that would let a
	corrupted key file decode "successfully" to a different seed
	than the producer intended.

	Raises `ValueError` on bad base64, embedded non-base64 chars,
	wrong decoded length, or read failure so a single failure
	surface covers all signers.
	"""
	from lang.drift.crypto import b64_decode
	try:
		seed_text = key_seed_path.read_text(encoding="utf-8").strip()
	except OSError as err:
		raise ValueError(f"signing key file unreadable: {err}") from err
	try:
		seed_bytes = b64_decode(seed_text)
	except Exception as err:
		raise ValueError(f"signing key file does not contain valid base64: {err}") from err
	if len(seed_bytes) != 32:
		raise ValueError(
			f"signing key seed must decode to 32 bytes, got {len(seed_bytes)}"
		)
	return seed_bytes


def extract_pubkey_from_seed(key_seed_path: Path) -> bytes:
	"""
	Extract the Ed25519 public key from a seed file.

	The seed file contains a base64-encoded 32-byte Ed25519 seed.
	"""
	from lang.drift.crypto import ed25519_sign_from_seed

	seed_bytes = load_signing_key_seed(key_seed_path)
	# Sign a dummy message to extract the public key.
	_sig, pubkey = ed25519_sign_from_seed(priv_seed32=seed_bytes, message=b"")
	return pubkey
